In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [27]:
#Evenly step
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((4))

array([0., 0., 0., 0.])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
#Evenly spaced array
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.random.rand(5)

array([0.11631909, 0.35543491, 0.93364875, 0.26817998, 0.44399532])

In [36]:
#random number from univorm distribution in range 0 to 1
np.random.rand(5,5)

array([[0.66724449, 0.0851928 , 0.23686327, 0.36013474, 0.43707644],
       [0.79266342, 0.28564928, 0.82927103, 0.09963971, 0.34081648],
       [0.33141392, 0.29873566, 0.55981407, 0.82792424, 0.11513907],
       [0.40982466, 0.91561487, 0.67735156, 0.99861026, 0.5194218 ],
       [0.20131814, 0.37608416, 0.68715781, 0.06570712, 0.67394243]])

In [37]:
#random number from normal distribution
np.random.randn(4,4)

array([[-0.03113314, -1.43777624, -0.7433665 ,  0.54263269],
       [ 0.98719679, -0.56640662, -0.4451239 , -0.97774713],
       [ 0.0765583 , -0.58868777,  0.12266947, -2.05953131],
       [ 0.80586127,  0.47234222,  0.39899814, -1.09392357]])

In [38]:
#random integer number from (a,) to (,b,) for (,c) amount
np.random.randint(1,100,10)

array([79, 16, 24, 45, 76,  4, 60, 22,  5, 80])

In [40]:
arr = np.arange(25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr = np.random.randint(0,50,10)

In [43]:
ranarr

array([28, 34, 26,  8, 27, 49, 27, 35, 32, 23])

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr.max() #max value

49

In [48]:
ranarr.min() #minimum value

8

In [49]:
ranarr.mean() #mean of all values

28.9

In [50]:
ranarr.argmax() #location of index that has maximum value

5

In [51]:
ranarr.argmin()#location of index that has minimum value

3

In [53]:
arr = arr.reshape(5,5)

In [54]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
arr.dtype

dtype('int32')

In [56]:
from numpy.random import randint #to import randint as numpy.random

In [57]:
randint(2,10)

5